task :install do
end

namespace :publish do
  input = "src/EN-us/jquery-fundamentals-book.xml"
  xalan = "scripts/libs/xalan/xalan-j_2_7_1"
  xslthl_jar = "scripts/libs/xslthl/xslthl-2.0.2.jar"
  xsl = "scripts/libs/docbook-xsl/docbook-xsl-1.75.2"

  desc "Generate HTML output"
  task :html do
    xsl_all_in_one = "xsl/xhtml.xsl"
    output_all_in_one = "release/html/book.html"

    xsl_chunked = "xsl/xhtml-chunked.xsl"
    output_chunked = "release/html/index.html"

    file "#{xalan}/xalan.jar" do
      raise "Xalan not found. Run rake install"
    end

    # Ensure there is a directory for our output
    directory "release/html"
    file "release/html" do
      cp ["imgs", "style/*", "#{xsl}/images"], "release/html"
    end

    # Output chunked html
    sh <<-COMMAND
      java \
      -Djava.endorsed.dirs=#{xalan} \
        -cp "#{xalan}/xalan.jar;#{xalan}/xml-apis.jar;#{xalan}/xercesImpl.jar;#{xsl}/extensions/xalan27.jar;#{xslthl_jar}" \
        -Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XIncludeParserConfiguration \
       org.apache.xalan.xslt.Process \
        -in  #{input} \
        -out #{output_chunked} \
        -xsl #{xsl_chunked} \
      -param keep.relative.image.uris 0 \
        -param use.extensions 1 \
        -param highlight.xslthl.config "file://#{pwd}/scripts/libs/xslthl/highlighters/xslthl-config.xml" \
        -param highlight.source 1
    COMMAND

    # Output all-in-one html
    sh <<-COMMAND
      java \
      -Djava.endorsed.dirs=#{xalan} \
        -cp "#{xalan}/xalan.jar;#{xalan}/xml-apis.jar;#{xalan}/xercesImpl.jar;#{xsl}/extensions/xalan27.jar;#{xslthl_jar}" \
        -Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XIncludeParserConfiguration \
      org.apache.xalan.xslt.Process \
        -in  #{input} \
        -out #{output_all_in_one} \
        -xsl #{xsl_all_in_one} \
      -param keep.relative.image.uris 0 \
        -param use.extensions 1 \
        -param highlight.xslthl.config "file://#{pwd}/scripts/libs/xslthl/highlighters/xslthl-config.xml" \
        -param highlight.source 1
    COMMAND
  end

  desc "Generate ePub output"
  task :epub do
    epub = "#{xsl}/epub/bin/dbtoepub"
    output_epub = "release/epub/jquery-fundamentals-book.epub"

    directory "release/epub"
    directory "release/tmp"

    sh "#{epub} -c style/epub.css -o #{output_epub} #{input}"

    base = pwd
    cd "release/tmp" do
      # Add fonts and fix content.opf
      sh "unzip -a #{base}/#{output_epub}"
      cp "#{base}/fonts/*", "OEBPS/"
      sh "ls -la ../../fonts/fonts-elements.xml"
      sh "sed -e '/<manifest>/r ../../fonts/fonts-elements.xml' < OEBPS/content.opf > content.opf"
      mv "content.opf", "OEBPS/content.opf"
      sh "zip -r #{base}/#{output_epub} *"
    end

    remove_dir release/tmp
  end

  desc "Generate PDF output"
  task :pdf do
    xsl_fo = "xsl/fo.xsl"
    fop_dir = "scripts/libs/fop/fop-0.95"
    output_fo = "release/fo/jquery-fundamentals-book.fo"
    output_pdf = "release/pdf/jquery-fundamentals-book.pdf"

    directory "release/fo"
    directory "release/pdf"

    # Build .fo
    sh <<-COMMAND
      java \
      -Djava.endorsed.dirs=#{xalan} \
        -cp "#{xalan}/xalan.jar;#{xalan}/xml-apis.jar;#{xalan}/xercesImpl.jar;#{xsl}/extensions/xalan27.jar;#{xslthl_jar}" \
        -Dorg.apache.xerces.xni.parser.XMLParserConfiguration=org.apache.xerces.parsers.XIncludeParserConfiguration \
      org.apache.xalan.xslt.Process \
        -in #{input}  \
        -out #{output_fo} \
        -xsl #{xsl_fo} \
        -param use.extensions 1 \
        -param highlight.xslthl.config "file://#{pwd}/scripts/libs/xslthl/highlighters/xslthl-config.xml" \
        -param highlight.source 1
    COMMAND

    begin
      cp "imgs", fop
    rescue => e
      puts e
    end

    # Build PDF from .fo
    sh "#{fop_dir}/fop -fo #{output_fo} -pdf #{output_pdf}"
  end
end

desc "Publish in all formats"
task :publish => ["publish:html", "publish:epub", "publish:pdf"]
